name: Test GitHub Actions Runners

on:
  workflow_dispatch:

jobs:
    test-runners:
        runs-on: self-hosted-spot-runner
        steps:
        - name: Check Runner
          run: echo "Runner is working fine!"

        - name: Run tests
          run: |
            echo "Running tests..."

